version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    restart: unless-stopped

    networks:
      - mynewtwork

  devopsProject:
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/stationSki?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING.JPA.SHOW-SQL=true
      - SPRING.JPA.HIBERNATE.DDL-AUTO=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.profiles.active=prod
    image: "mohamedaouadi/devops_project"
    depends_on:
      - mysqldb
    networks:
      - mynewtwork
    volumes:
      - .m2:/root/.m2

networks:
  mynewtwork :
