version: '3'

services:

  mysqldb:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'stationSki'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  backend_spring:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stationSki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    volumes:
      - ./backend_spring_data:/app/data

volumes:
  db:
  backend_spring_data:

networks:
  my-network:
    driver: bridge

